### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by mayrsascha** [traviswimer/react-hydration-provider#2]
Hi

I have to say nice work on this! This would solve a big headache I'm currently facing with my site https://www.coinrotator.app/

Before I can use this though I'd need to know if this has been tested somewhere in production. Do you have any or know of any site using it?

Thanks

**Comment by traviswimer** [comment]
@mayrsascha I'm using it on my [portfolio/blog site](https://traviswimer.com/). It's not a high-traffic site or anything, but I haven't had any problems.

`react-hydration-provider` has been getting a decent number of downloads on NPM and no one has opened any issues yet, which I assume is a good sign.

If you're concerned about it, I'd recommend taking a look at the code, as this is a small package with little code.

Or, if you'd rather code your own implementation, you can take a look at my [blog post](https://traviswimer.com/blog/easily-fix-react-hydration-errors/) that explains the concepts behind this package.

**Comment by mayrsascha** [comment]
@traviswimer Thank you for your comprehensive answer!

I see that there are indeed no issues that were opened and the code itself seems rather simple also, and I understand what's behind it.

My main concern is really if this will be maintained. I got burned before by using packages that don't have many stars on GH / aren't that popular and authors decided (very understandably and probably for various reasons) to not keep on maintaining these projects when say, React upgrades to the next version or there is a security concern, etc.

Seeing that you wrote a blog post about it, it's part of your developer portfolio and that you replied quickly with an answer that makes sense I tend to trust you here in that you would keep maintaining this package at least for some time and/or accept PRs that fix things.

Thank you, closing this one for now.
